### PR TITLE
fix paths separator on windows

### PR DESCRIPTION
**Pull request by mikolaj6r**

### CODE REVIEW

**Comment by pmowrer** [comment]
Thanks for the contribution @mikolaj6r! This repo uses [semantic-release](https://github.com/semantic-release/semantic-release) to automagically release a new version on merge. To trigger a release, commits must follow a specific format (I need to add a CONTRIBUTING where this is outlined). 

TLDR; please merge the commits into one and update the commit message to:
`fix: paths separator on windows` 😄

**Comment by faebeee** [comment]
Hello everyone. Whats the status on this one? We could really use this fix

**Comment by pmowrer** [comment]
@faebeee Feel free to jump on this. This exact PR with an updated commit message per the instructions above will get merged.

**Comment by faebeee** [comment]
@pmowrer  here you go: https://github.com/pmowrer/node-sass-json-importer/pull/90

**Comment by pmowrer** [comment]
Thanks @faebeee!

**Pull request closed without merging**
